"""Frozen pole regressions: mpmath==1.3.0 at requested+240/+400 dps.
Developer-only; tests consume the generated C header without Python.
"""
from decimal import Decimal, localcontext, ROUND_DOWN, ROUND_UP, ROUND_FLOOR, ROUND_CEILING, ROUND_HALF_UP, ROUND_HALF_EVEN
from pathlib import Path
import mpmath as mp

INPUTS = (
    "1.5707963267948966192313216916397514420985",
    "1.5707963267948966192313216916397514420986",
    "-1.5707963267948966192313216916397514420985",
    "4.7123889803846898576939650749192543262957",
    "1.570796326794896619231321691639751442098585",
)
MODES = (ROUND_DOWN, ROUND_UP, ROUND_FLOOR, ROUND_CEILING, ROUND_HALF_UP, ROUND_HALF_EVEN)

def rounded(text, digits, mode, extra):
    with mp.workdps(digits + extra):
        raw = mp.nstr(mp.tan(mp.mpf(text)), digits + extra - 10)
    with localcontext() as context:
        context.prec = digits + extra
        value = Decimal(raw)
        return format(value.quantize(Decimal(1).scaleb(value.adjusted()-digits+1), rounding=mode).normalize(), 'f')

def main():
    if mp.__version__ != "1.3.0": raise RuntimeError("Use mpmath==1.3.0")
    rows = []
    for text in INPUTS:
        for digits in (10, 30, 100):
            for mode, rounding in enumerate(MODES):
                expected = rounded(text, digits, rounding, 240)
                if expected != rounded(text, digits, rounding, 400): raise RuntimeError("Unstable reference")
                rows.append(f'    {{"{text}", {digits}, {mode}, "{expected}"}},')
    Path(__file__).with_name("tangent_references.h").write_text(
        "/* Generated by generate_tangent_references.py; mpmath 1.3.0, +240/+400 dps. */\n"
        "static const struct { const char *input; int64_t digits; int rounding; const char *expected; } tangent_references[] = {\n"
        + "\n".join(rows) + "\n};\n", encoding="utf-8")

if __name__ == "__main__": main()
