"""Regenerate transcendental_references.tsv with mpmath 1.3.0.

This is a developer-only generator. CTest reads the checked-in TSV and needs
only Node.js; it never imports mpmath. Run with at least 300 decimal digits.
"""

from decimal import (
    Decimal, ROUND_CEILING, ROUND_DOWN, ROUND_FLOOR, ROUND_HALF_EVEN,
    ROUND_HALF_UP, ROUND_UP, localcontext,
)
from pathlib import Path

import mpmath as mp

if mp.__version__ != "1.3.0":
    raise RuntimeError("Regenerate with mpmath==1.3.0")


ROUNDING = (ROUND_DOWN, ROUND_UP, ROUND_FLOOR, ROUND_CEILING,
            ROUND_HALF_UP, ROUND_HALF_EVEN)

# Inputs are decimal literals, never values computed by NumForge. Categories:
# near domain boundaries, cancellation around ln(1), tiny arguments, large
# angles, large hyperbolic arguments and ordinary interior points.
UNARY = {
    "exp": ["-100", "-1", "-1E-25", "0", "1E-25", "0.693147180559945309417232", "1", "20"],
    "ln": ["1E-30", "0.5", "0.9999999999999999999999999", "1", "1.0000000000000000000000001", "2", "10", "1E30"],
    "log10": ["1E-30", "0.1", "0.9999999999999999999999999", "1", "1.0000000000000000000000001", "2", "1E30"],
    "sin": ["-1E-25", "0", "1E-25", "0.5", "3.141592653589793238462643383279", "1E20"],
    "cos": ["-1E-25", "0", "1E-25", "0.5", "3.141592653589793238462643383279", "1E20"],
    "tan": ["-1E-25", "0", "1E-25", "0.5", "1.570796326794896619231321691639", "1E20"],
    "asin": ["-1", "-0.99999999999999999999", "-1E-25", "0", "0.5", "0.99999999999999999999", "1"],
    "acos": ["-1", "-0.99999999999999999999", "0", "0.5", "0.99999999999999999999", "1"],
    "atan": ["-1E30", "-1", "-1E-25", "0", "1E-25", "1", "1E30"],
    "sinh": ["-100", "-1", "-1E-25", "0", "1E-25", "1", "100"],
    "cosh": ["-100", "-1", "-1E-25", "0", "1E-25", "1", "100"],
    "tanh": ["-100", "-1", "-1E-25", "0", "1E-25", "1", "100"],
    "asinh": ["-1E30", "-1", "-1E-25", "0", "1E-25", "1", "1E30"],
    "acosh": ["1", "1.00000000000000000001", "2", "1E30"],
    "atanh": ["-0.99999999999999999999", "-0.5", "-1E-25", "0", "1E-25", "0.5", "0.99999999999999999999"],
}
BINARY = [("log", "8", "2"), ("log", "2", "10"),
          ("log", "1.0000000000000000000000001", "1.0000000000000000000000002"),
          ("log", "1E-20", "0.5")]
DOMAINS = [("ln", "0", "0"), ("ln", "-1", "0"),
           ("log10", "0", "0"), ("log", "2", "1"),
           ("log", "-2", "3"), ("log", "2", "-3"),
           ("asin", "1.00000000000000000001", "0"),
           ("acos", "-1.00000000000000000001", "0"),
           ("acosh", "0.99999999999999999999", "0"),
           ("atanh", "1", "0"), ("atanh", "-1", "0")]


def evaluate(op, a, b):
    x = mp.mpf(a)
    if op == "log":
        return mp.log(x, mp.mpf(b))
    if op == "log10":
        return mp.log10(x)
    return getattr(mp, op)(x)


def rounded(op, a, b, digits, mode, dps):
    with mp.workdps(dps), localcontext() as context:
        context.prec = dps + 20
        value = evaluate(op, a, b)
        decimal = Decimal(mp.nstr(value, dps - 30, strip_zeros=False))
        if decimal.is_zero():
            return "0"
        quantum = Decimal(1).scaleb(decimal.adjusted() - digits + 1)
        result = decimal.quantize(quantum, rounding=ROUNDING[mode]).normalize()
        return format(result, "f")


def main():
    rows = []
    def add(op, a, b, digits, mode):
        expected = rounded(op, a, b, digits, mode, 220)
        if expected != rounded(op, a, b, digits, mode, 300):
            raise ValueError(f"Unstable reference: {op} {a} {b} {digits} {mode}")
        rows.append((op, a, b, digits, mode, expected))

    for op, inputs in UNARY.items():
        for a in inputs:
            add(op, a, "0", 24, 5)
        # A signed ordinary value exercises every directed and tie mode.
        for a in (inputs[0], inputs[-1]):
            for mode in range(6):
                add(op, a, "0", 12, mode)
    for op, a, b in BINARY:
        add(op, a, b, 24, 5)
        for mode in range(6):
            add(op, a, b, 12, mode)
    for op, a, b in DOMAINS:
        rows.append((op, a, b, 24, 5, "ERROR 3"))

    output = Path(__file__).with_name("transcendental_references.tsv")
    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# NumForge independent reference: mpmath 1.3.0, 220/300 decimal digits.\n")
        stream.write("# Generated by tests/generate_transcendental_references.py.\n")
        stream.write("# op input base_or_zero significant_digits rounding_mode expected\n")
        for row in rows:
            stream.write("\t".join(map(str, row)) + "\n")
    print(f"Wrote {len(rows)} cases to {output}")


if __name__ == "__main__":
    main()
