"""Frozen angle-conversion regressions: mpmath==1.3.0 at requested+240/+400 dps.
Developer-only; tests consume the generated C header without Python.
"""
from decimal import Decimal, localcontext, ROUND_DOWN, ROUND_UP, ROUND_FLOOR, ROUND_CEILING, ROUND_HALF_UP, ROUND_HALF_EVEN
from pathlib import Path
import mpmath as mp

INPUTS = (
    ("1", "deg", "rad"),
    ("-1", "deg", "rad"),
    ("1", "rad", "deg"),
    ("-1", "rad", "deg"),
    ("1e-1000", "deg", "rad"),
    ("1e1000", "rad", "turn"),
)
MODES = (ROUND_DOWN, ROUND_UP, ROUND_FLOOR, ROUND_CEILING, ROUND_HALF_UP, ROUND_HALF_EVEN)

def rounded(text, source, target, digits, mode, extra):
    with mp.workdps(digits + extra):
        factors = {"rad": mp.mpf(1), "deg": mp.pi / 180, "turn": 2 * mp.pi}
        raw = mp.nstr(mp.mpf(text) * factors[source] / factors[target], digits + extra - 10)
    with localcontext() as context:
        context.prec = digits + extra
        value = Decimal(raw)
        return format(value.quantize(Decimal(1).scaleb(value.adjusted()-digits+1), rounding=mode).normalize(), 'f')

def main():
    if mp.__version__ != "1.3.0": raise RuntimeError("Use mpmath==1.3.0")
    rows = []
    for text, source, target in INPUTS:
        for digits in (10, 30, 100, 501):
            if digits == 501 and text != "1": continue
            for mode, rounding in enumerate(MODES):
                expected = rounded(text, source, target, digits, rounding, 240)
                if expected != rounded(text, source, target, digits, rounding, 400): raise RuntimeError("Unstable reference")
                rows.append(f'    {{"{text}", "{source}", "{target}", {digits}, {mode}, "{expected}"}},')
    Path(__file__).with_name("unit_angle_references.h").write_bytes((
        "/* Generated by generate_unit_angle_references.py; mpmath 1.3.0, +240/+400 dps. */\n"
        "static const struct { const char *input; const char *from; const char *to; int64_t digits; int rounding; const char *expected; } unit_angle_references[] = {\n"
        + "\n".join(rows) + "\n};\n").encode("utf-8"))

if __name__ == "__main__": main()
