#ifndef NUMFORGE_WEB_PAGE_H
#define NUMFORGE_WEB_PAGE_H

#include <stddef.h>

/*
------------------------------------------------------------------------------------------------------------------------------
    Small calculator and API-guide pages embedded in the server executable.
    Keeping them here makes numforge_web self-contained: no Node.js, assets,
    or working-directory setup is required to use the local calculator.
------------------------------------------------------------------------------------------------------------------------------
*/
/*
------------------------------------------------------------------------------------------------------------------------------
    Slovak calculator markup and layout.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char NUMFORGE_WEB_PAGE_START[] =
    "<!doctype html>\n"
    "<html lang=\"sk\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge</title>\n"
    "  <style>\n"
    "    :root\n"
    "    {\n"
    "        color-scheme: dark;\n"
    "        font-family: system-ui, sans-serif;\n"
    "    }\n"
    "\n"
    "    body\n"
    "    {\n"
    "        max-width: 720px;\n"
    "        margin: 0 auto;\n"
    "        padding: 48px 20px;\n"
    "        background: #111318;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    .page-header\n"
    "    {\n"
    "        display: flex;\n"
    "        flex-wrap: wrap;\n"
    "        align-items: center;\n"
    "        justify-content: space-between;\n"
    "        gap: 14px;\n"
    "    }\n"
    "\n"
    "    h1\n"
    "    {\n"
    "        margin: 0;\n"
    "        color: #ff9d36;\n"
    "    }\n"
    "\n"
    "    .language-switch\n"
    "    {\n"
    "        display: flex;\n"
    "        gap: 6px;\n"
    "    }\n"
    "\n"
    "    .language-switch a\n"
    "    {\n"
    "        padding: 6px 9px;\n"
    "        border: 1px solid #3b4352;\n"
    "        border-radius: 6px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .9rem;\n"
    "        text-decoration: none;\n"
    "    }\n"
    "\n"
    "    .language-switch a[aria-current=\"true\"]\n"
    "    {\n"
    "        border-color: #ff9d36;\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    p\n"
    "    {\n"
    "        color: #adb5c3;\n"
    "        line-height: 1.55;\n"
    "    }\n"
    "\n"
    "    a\n"
    "    {\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    form\n"
    "    {\n"
    "        display: flex;\n"
    "        gap: 10px;\n"
    "        margin-top: 28px;\n"
    "    }\n"
    "\n"
    "    input\n"
    "    {\n"
    "        min-width: 0;\n"
    "        flex: 1;\n"
    "        padding: 13px;\n"
    "        border: 1px solid #3b4352;\n"
    "        border-radius: 8px;\n"
    "        background: #1c2028;\n"
    "        color: inherit;\n"
    "        font: 1rem ui-monospace, monospace;\n"
    "    }\n"
    "\n"
    "    button\n"
    "    {\n"
    "        padding: 12px 18px;\n"
    "        border: 0;\n"
    "        border-radius: 8px;\n"
    "        background: #ff9d36;\n"
    "        color: #17110a;\n"
    "        font-weight: 700;\n"
    "        cursor: pointer;\n"
    "    }\n"
    "\n"
    "    .precision\n"
    "    {\n"
    "        display: flex;\n"
    "        flex-wrap: wrap;\n"
    "        align-items: center;\n"
    "        gap: 10px 16px;\n"
    "        margin-top: 14px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .92rem;\n"
    "    }\n"
    "\n"
    "    .precision label\n"
    "    {\n"
    "        display: flex;\n"
    "        align-items: center;\n"
    "        gap: 7px;\n"
    "    }\n"
    "\n"
    "    .precision input[type=number]\n"
    "    {\n"
    "        width: 6.5rem;\n"
    "        flex: none;\n"
    "        padding: 8px;\n"
    "    }\n"
    "\n"
    "    .precision input[type=checkbox]\n"
    "    {\n"
    "        width: auto;\n"
    "        flex: none;\n"
    "    }\n"
    "\n"
    "    .keypad\n"
    "    {\n"
    "        display: grid;\n"
    "        grid-template-columns: repeat(5, minmax(0, 1fr));\n"
    "        gap: 8px;\n"
    "        margin-top: 14px;\n"
    "    }\n"
    "\n"
    "    .keypad button\n"
    "    {\n"
    "        padding: 12px 6px;\n"
    "        background: #282e39;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    .keypad button.operator, .keypad button.equals\n"
    "    {\n"
    "        background: #ff9d36;\n"
    "        color: #17110a;\n"
    "    }\n"
    "\n"
    "    .keypad button.action\n"
    "    {\n"
    "        background: #414b5c;\n"
    "    }\n"
    "\n"
    "    .keypad button.future\n"
    "    {\n"
    "        color: #7d8798;\n"
    "        background: #1a1e26;\n"
    "        cursor: not-allowed;\n"
    "    }\n"
    "\n"
    "    .keypad.constants\n"
    "    {\n"
    "        grid-template-columns: repeat(3, minmax(0, 1fr));\n"
    "    }\n"
    "\n"
    "    .keypad-label\n"
    "    {\n"
    "        margin: 24px 0 8px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .84rem;\n"
    "        font-weight: 700;\n"
    "        text-transform: uppercase;\n"
    "        letter-spacing: .08em;\n"
    "    }\n"
    "\n"
    "    .result-panel\n"
    "    {\n"
    "        margin-top: 22px;\n"
    "        padding: 16px;\n"
    "        border-radius: 8px;\n"
    "        background: #1c2028;\n"
    "    }\n"
    "\n"
    "    .result-label\n"
    "    {\n"
    "        display: block;\n"
    "        margin-bottom: 7px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .84rem;\n"
    "        font-weight: 700;\n"
    "        text-transform: uppercase;\n";

static const char NUMFORGE_WEB_PAGE_START_CONT_1[] =
    "        letter-spacing: .08em;\n"
    "    }\n"
    "\n"
    "    #result\n"
    "    {\n"
    "        display: block;\n"
    "        min-height: 7.5em;\n"
    "        max-height: 7.5em;\n"
    "        font: 1.2rem/1.5 ui-monospace, monospace;\n"
    "        overflow: hidden;\n"
    "        overflow-wrap: anywhere;\n"
    "        cursor: pointer;\n"
    "    }\n"
    "\n"
    "    #result.expanded\n"
    "    {\n"
    "        max-height: none;\n"
    "    }\n"
    "\n"
    "    #expand-result\n"
    "    {\n"
    "        display: none;\n"
    "        margin-top: 9px;\n"
    "        padding: 6px 9px;\n"
    "        font-size: .82rem;\n"
    "    }\n"
    "\n"
    "    #result.error\n"
    "    {\n"
    "        color: #ff8888;\n"
    "    }\n"
    "\n"
    "    .guide-link\n"
    "    {\n"
    "        display: inline-block;\n"
    "        margin-top: 22px;\n"
    "    }\n"
    "\n"
    "    code, pre\n"
    "    {\n"
    "        border-radius: 6px;\n"
    "        background: #1c2028;\n"
    "        font-family: ui-monospace, monospace;\n"
    "    }\n"
    "\n"
    "    code\n"
    "    {\n"
    "        padding: 2px 5px;\n"
    "    }\n"
    "\n"
    "    pre\n"
    "    {\n"
    "        padding: 14px;\n"
    "        overflow-x: auto;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <header class=\"page-header\">\n"
    "    <h1>NumForge</h1>\n"
    "    <nav class=\"language-switch\" aria-label=\"Výber jazyka\"><a href=\"/?lang=sk\" lang=\"sk\" "
    "aria-current=\"true\" title=\"Slovenčina\">🇸🇰 SK</a><a href=\"/?lang=en\" lang=\"en\" title=\"English\">🇬🇧 "
    "EN</a></nav>\n"
    "  </header>\n"
    "  <p>Zapíš výraz a NumForge ho vyhodnotí priamo cez C parser a presný BigDecimal.</p>\n"
    "  <form id=\"calculator\">\n"
    "    <input id=\"expression\" aria-label=\"Matematický výraz\" autocomplete=\"off\" autofocus>\n"
    "    <button type=\"submit\">Vypočítať</button>\n"
    "  </form>\n";

static const char NUMFORGE_WEB_PAGE_PRECISION[] =
    "  <section class=\"precision\" aria-label=\"Nastavenie výstupnej presnosti\">\n"
    "    <label>Desatinné miesta <input id=\"precision\" type=\"number\" min=\"0\" max=\"10000\" step=\"1\" "
    "value=\"10\" inputmode=\"numeric\"></label>\n"
    "    <label><input id=\"full-precision\" type=\"checkbox\"> Plný výstup</label>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_RESULT[] =
    "  <section class=\"result-panel\" aria-live=\"polite\">\n"
    "    <div style=\"display:flex;align-items:center;justify-content:space-between;gap:12px\">\n"
    "      <span class=\"result-label\">Výsledok</span><button id=\"copy-result\" type=\"button\" disabled "
    "title=\"Skopírovať výsledok\" aria-label=\"Skopírovať výsledok\" style=\"padding:6px "
    "9px;font-size:.82rem\">⧉ Kopírovať</button>\n"
    "    </div>\n"
    "    <output id=\"result\"></output><button id=\"expand-result\" type=\"button\">Zobraziť všetko</button>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_KEYPAD[] =
    "  <section class=\"keypad\" aria-label=\"Kalkulačná klávesnica\">\n"
    "    <button type=\"button\" class=\"operator\" data-insert=\"(\">(</button><button type=\"button\" "
    "class=\"operator\" data-insert=\")\">)</button><button type=\"button\" data-insert=\".\">.</button><button "
    "type=\"button\" class=\"action\" data-action=\"clear\">C</button><button type=\"button\" class=\"action\" "
    "data-action=\"backspace\" aria-label=\"Vymazať posledný znak\">⌫</button>\n"
    "  </section>\n"
    "  <section class=\"keypad\" aria-label=\"Číselná klávesnica\">\n"
    "    <button type=\"button\" data-insert=\"7\">7</button><button type=\"button\" "
    "data-insert=\"8\">8</button><button type=\"button\" data-insert=\"9\">9</button><button type=\"button\" "
    "class=\"operator\" data-insert=\"/\">÷</button><button type=\"button\" class=\"operator\" "
    "data-insert=\"*\">×</button>\n"
    "    <button type=\"button\" data-insert=\"4\">4</button><button type=\"button\" "
    "data-insert=\"5\">5</button><button type=\"button\" data-insert=\"6\">6</button><button type=\"button\" "
    "class=\"operator\" data-insert=\"-\">−</button><button type=\"button\" class=\"operator\" "
    "data-insert=\"+\">+</button>\n"
    "    <button type=\"button\" data-insert=\"1\">1</button><button type=\"button\" "
    "data-insert=\"2\">2</button><button type=\"button\" data-insert=\"3\">3</button><button type=\"button\" "
    "data-insert=\"0\">0</button><button type=\"button\" class=\"equals\" data-action=\"evaluate\">=</button>\n"
    "  </section>\n"
    "  <p class=\"keypad-label\">Konštanty</p>\n"
    "  <section class=\"keypad constants\" aria-label=\"Matematické konštanty\">\n"
    "    <button type=\"button\" data-insert=\"&#960;\" title=\"π\">π</button><button type=\"button\" "
    "data-insert=\"e\" title=\"Eulerovo číslo\">e</button><button type=\"button\" data-insert=\"&#966;\" "
    "title=\"φ\">φ</button>\n"
    "  </section>\n";

/*
------------------------------------------------------------------------------------------------------------------------------
    English calculator markup and layout.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char NUMFORGE_WEB_PAGE_EN_START[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge</title>\n"
    "  <style>\n"
    "    :root\n"
    "    {\n"
    "        color-scheme: dark;\n"
    "        font-family: system-ui, sans-serif;\n"
    "    }\n"
    "\n"
    "    body\n"
    "    {\n"
    "        max-width: 720px;\n"
    "        margin: 0 auto;\n"
    "        padding: 48px 20px;\n"
    "        background: #111318;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    .page-header\n"
    "    {\n"
    "        display: flex;\n"
    "        flex-wrap: wrap;\n"
    "        align-items: center;\n"
    "        justify-content: space-between;\n"
    "        gap: 14px;\n"
    "    }\n"
    "\n"
    "    h1\n"
    "    {\n"
    "        margin: 0;\n"
    "        color: #ff9d36;\n"
    "    }\n"
    "\n"
    "    p\n"
    "    {\n"
    "        color: #adb5c3;\n"
    "        line-height: 1.55;\n"
    "    }\n"
    "\n"
    "    a\n"
    "    {\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    .language-switch\n"
    "    {\n"
    "        display: flex;\n"
    "        gap: 6px;\n"
    "    }\n"
    "\n"
    "    .language-switch a\n"
    "    {\n"
    "        padding: 6px 9px;\n"
    "        border: 1px solid #3b4352;\n"
    "        border-radius: 6px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .9rem;\n"
    "        text-decoration: none;\n"
    "    }\n"
    "\n"
    "    .language-switch a[aria-current=\"true\"]\n"
    "    {\n"
    "        border-color: #ff9d36;\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    form\n"
    "    {\n"
    "        display: flex;\n"
    "        gap: 10px;\n"
    "        margin-top: 28px;\n"
    "    }\n"
    "\n"
    "    input\n"
    "    {\n"
    "        min-width: 0;\n"
    "        flex: 1;\n"
    "        padding: 13px;\n"
    "        border: 1px solid #3b4352;\n"
    "        border-radius: 8px;\n"
    "        background: #1c2028;\n"
    "        color: inherit;\n"
    "        font: 1rem ui-monospace, monospace;\n"
    "    }\n"
    "\n"
    "    button\n"
    "    {\n"
    "        padding: 12px 18px;\n"
    "        border: 0;\n"
    "        border-radius: 8px;\n"
    "        background: #ff9d36;\n"
    "        color: #17110a;\n"
    "        font-weight: 700;\n"
    "        cursor: pointer;\n"
    "    }\n"
    "\n"
    "    .precision\n"
    "    {\n"
    "        display: flex;\n"
    "        flex-wrap: wrap;\n"
    "        align-items: center;\n"
    "        gap: 10px 16px;\n"
    "        margin-top: 14px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .92rem;\n"
    "    }\n"
    "\n"
    "    .precision label\n"
    "    {\n"
    "        display: flex;\n"
    "        align-items: center;\n"
    "        gap: 7px;\n"
    "    }\n"
    "\n"
    "    .precision input[type=number]\n"
    "    {\n"
    "        width: 6.5rem;\n"
    "        flex: none;\n"
    "        padding: 8px;\n"
    "    }\n"
    "\n"
    "    .precision input[type=checkbox]\n"
    "    {\n"
    "        width: auto;\n"
    "        flex: none;\n"
    "    }\n"
    "\n"
    "    .keypad\n"
    "    {\n"
    "        display: grid;\n"
    "        grid-template-columns: repeat(5, minmax(0, 1fr));\n"
    "        gap: 8px;\n"
    "        margin-top: 14px;\n"
    "    }\n"
    "\n"
    "    .keypad button\n"
    "    {\n"
    "        padding: 12px 6px;\n"
    "        background: #282e39;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    .keypad button.operator, .keypad button.equals\n"
    "    {\n"
    "        background: #ff9d36;\n"
    "        color: #17110a;\n"
    "    }\n"
    "\n"
    "    .keypad button.action\n"
    "    {\n"
    "        background: #414b5c;\n"
    "    }\n"
    "\n"
    "    .keypad button.future\n"
    "    {\n"
    "        color: #7d8798;\n"
    "        background: #1a1e26;\n"
    "        cursor: not-allowed;\n"
    "    }\n"
    "\n"
    "    .keypad.constants\n"
    "    {\n"
    "        grid-template-columns: repeat(3, minmax(0, 1fr));\n"
    "    }\n"
    "\n"
    "    .keypad-label\n"
    "    {\n"
    "        margin: 24px 0 8px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .84rem;\n"
    "        font-weight: 700;\n"
    "        text-transform: uppercase;\n"
    "        letter-spacing: .08em;\n"
    "    }\n"
    "\n"
    "    .result-panel\n"
    "    {\n"
    "        margin-top: 22px;\n"
    "        padding: 16px;\n"
    "        border-radius: 8px;\n"
    "        background: #1c2028;\n"
    "    }\n"
    "\n"
    "    .result-label\n"
    "    {\n"
    "        display: block;\n"
    "        margin-bottom: 7px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .84rem;\n"
    "        font-weight: 700;\n"
    "        text-transform: uppercase;\n";

static const char NUMFORGE_WEB_PAGE_EN_START_CONT_1[] =
    "        letter-spacing: .08em;\n"
    "    }\n"
    "\n"
    "    #result\n"
    "    {\n"
    "        display: block;\n"
    "        min-height: 7.5em;\n"
    "        max-height: 7.5em;\n"
    "        font: 1.2rem/1.5 ui-monospace, monospace;\n"
    "        overflow: hidden;\n"
    "        overflow-wrap: anywhere;\n"
    "        cursor: pointer;\n"
    "    }\n"
    "\n"
    "    #result.expanded\n"
    "    {\n"
    "        max-height: none;\n"
    "    }\n"
    "\n"
    "    #expand-result\n"
    "    {\n"
    "        display: none;\n"
    "        margin-top: 9px;\n"
    "        padding: 6px 9px;\n"
    "        font-size: .82rem;\n"
    "    }\n"
    "\n"
    "    #result.error\n"
    "    {\n"
    "        color: #ff8888;\n"
    "    }\n"
    "\n"
    "    .guide-link\n"
    "    {\n"
    "        display: inline-block;\n"
    "        margin-top: 22px;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <header class=\"page-header\">\n"
    "    <h1>NumForge</h1>\n"
    "    <nav class=\"language-switch\" aria-label=\"Language selection\"><a href=\"/?lang=sk\" lang=\"sk\" "
    "title=\"Slovenčina\">🇸🇰 SK</a><a href=\"/?lang=en\" lang=\"en\" aria-current=\"true\" title=\"English\">🇬🇧 "
    "EN</a></nav>\n"
    "  </header>\n"
    "  <p>Enter an expression and NumForge evaluates it directly with its C parser and exact BigDecimal.</p>\n"
    "  <form id=\"calculator\">\n"
    "    <input id=\"expression\" aria-label=\"Mathematical expression\" autocomplete=\"off\" autofocus>\n"
    "    <button type=\"submit\">Calculate</button>\n"
    "  </form>\n";

static const char NUMFORGE_WEB_PAGE_EN_PRECISION[] =
    "  <section class=\"precision\" aria-label=\"Output precision settings\">\n"
    "    <label>Decimal places <input id=\"precision\" type=\"number\" min=\"0\" max=\"10000\" step=\"1\" "
    "value=\"10\" inputmode=\"numeric\"></label>\n"
    "    <label><input id=\"full-precision\" type=\"checkbox\"> Full output</label>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_EN_RESULT[] =
    "  <section class=\"result-panel\" aria-live=\"polite\">\n"
    "    <div style=\"display:flex;align-items:center;justify-content:space-between;gap:12px\">\n"
    "      <span class=\"result-label\">Result</span><button id=\"copy-result\" type=\"button\" disabled "
    "title=\"Copy result\" aria-label=\"Copy result\" style=\"padding:6px 9px;font-size:.82rem\">⧉ Copy</button>\n"
    "    </div>\n"
    "    <output id=\"result\"></output><button id=\"expand-result\" type=\"button\">Show all</button>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_EN_KEYPAD[] =
    "  <section class=\"keypad\" aria-label=\"Calculator keypad\">\n"
    "    <button type=\"button\" class=\"operator\" data-insert=\"(\">(</button><button type=\"button\" "
    "class=\"operator\" data-insert=\")\">)</button><button type=\"button\" data-insert=\".\">.</button><button "
    "type=\"button\" class=\"action\" data-action=\"clear\">C</button><button type=\"button\" class=\"action\" "
    "data-action=\"backspace\" aria-label=\"Delete last character\">⌫</button>\n"
    "  </section>\n"
    "  <section class=\"keypad\" aria-label=\"Number keypad\">\n"
    "    <button type=\"button\" data-insert=\"7\">7</button><button type=\"button\" "
    "data-insert=\"8\">8</button><button type=\"button\" data-insert=\"9\">9</button><button type=\"button\" "
    "class=\"operator\" data-insert=\"/\">÷</button><button type=\"button\" class=\"operator\" "
    "data-insert=\"*\">×</button>\n"
    "    <button type=\"button\" data-insert=\"4\">4</button><button type=\"button\" "
    "data-insert=\"5\">5</button><button type=\"button\" data-insert=\"6\">6</button><button type=\"button\" "
    "class=\"operator\" data-insert=\"-\">−</button><button type=\"button\" class=\"operator\" "
    "data-insert=\"+\">+</button>\n"
    "    <button type=\"button\" data-insert=\"1\">1</button><button type=\"button\" "
    "data-insert=\"2\">2</button><button type=\"button\" data-insert=\"3\">3</button><button type=\"button\" "
    "data-insert=\"0\">0</button><button type=\"button\" class=\"equals\" data-action=\"evaluate\">=</button>\n"
    "  </section>\n"
    "  <p class=\"keypad-label\">Constants</p>\n"
    "  <section class=\"keypad constants\" aria-label=\"Mathematical constants\">\n"
    "    <button type=\"button\" data-insert=\"&#960;\" title=\"π\">π</button><button type=\"button\" "
    "data-insert=\"e\" title=\"Euler's number\">e</button><button type=\"button\" data-insert=\"&#966;\" "
    "title=\"φ\">φ</button>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_EN_FUTURE[] =
    "  <p class=\"keypad-label\">Functions and operations</p>\n"
    "  <section class=\"keypad\" aria-label=\"Functions and operations\">\n"
    "    <button type=\"button\" data-insert=\"^\" title=\"Power: exponent must be a non-negative "
    "integer\">xʸ</button><button type=\"button\" data-insert=\"&#178;\" title=\"Square\">x²</button><button "
    "type=\"button\" data-insert=\"&#179;\" title=\"Cube\">x³</button><button type=\"button\" data-insert=\"!\" "
    "title=\"Factorial\">n!</button><button type=\"button\" data-insert=\";\" title=\"Argument separator\">;</button>\n"
    "  </section>\n";

static const char NUMFORGE_WEB_PAGE_FUTURE[] =
    "  <p class=\"keypad-label\">Funkcie a operácie</p>\n"
    "  <section class=\"keypad\" aria-label=\"Funkcie a operácie\">\n"
    "    <button type=\"button\" data-insert=\"^\" title=\"Mocnina: exponent musí byť nezáporné celé "
    "číslo\">xʸ</button><button type=\"button\" data-insert=\"&#178;\" title=\"Druhá "
    "mocnina\">x²</button><button type=\"button\" data-insert=\"&#179;\" title=\"Tretia "
    "mocnina\">x³</button><button type=\"button\" data-insert=\"!\" title=\"Faktoriál\">n!</button><button "
    "type=\"button\" data-insert=\";\" title=\"Oddeľovač argumentov\">;</button>\n"
    "  </section>\n";

/*
------------------------------------------------------------------------------------------------------------------------------
    Function controls shared in structure by the Slovak and English pages.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char NUMFORGE_WEB_PAGE_FUNCTIONS_0[] =
    "<details class=\"function-group\"><summary>Základné</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"abs\" data-insert=\"abs(\" title=\"abs(x)\">abs</button>\n"
    "<button type=\"button\" data-function=\"sign\" data-insert=\"sign(\" title=\"sign(x)\">sign</button>\n"
    "<button type=\"button\" data-function=\"min\" data-insert=\"min(\" title=\"min(a;b;…)\">min</button>\n"
    "<button type=\"button\" data-function=\"max\" data-insert=\"max(\" title=\"max(a;b;…)\">max</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_FUNCTIONS_1[] =
    "<details class=\"function-group\"><summary>Celé čísla</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"gcd\" data-insert=\"gcd(\">gcd</button>\n"
    "<button type=\"button\" data-function=\"lcm\" data-insert=\"lcm(\">lcm</button>\n"
    "<button type=\"button\" data-function=\"mod\" data-insert=\"mod(\">mod</button>\n"
    "<button type=\"button\" data-function=\"factorial\" data-insert=\"factorial(\" "
    "title=\"factorial(n)\">factorial</button>\n"
    "<button type=\"button\" data-function=\"isqrt\" data-insert=\"isqrt(\">isqrt</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_FUNCTIONS_2[] =
    "<details class=\"function-group\"><summary>Mocniny a logaritmy</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"pow\" data-insert=\"pow(\" title=\"pow(x;y)\">pow</button>\n"
    "<button type=\"button\" data-function=\"sqrt\" data-insert=\"sqrt(\">sqrt</button>\n"
    "<button type=\"button\" data-function=\"cbrt\" data-insert=\"cbrt(\">cbrt</button>\n"
    "<button type=\"button\" data-function=\"root\" data-insert=\"root(\">root</button>\n"
    "<button type=\"button\" data-function=\"exp\" data-insert=\"exp(\" title=\"e umocnené na x\">exp</button>\n"
    "<button type=\"button\" data-function=\"ln\" data-insert=\"ln(\" title=\"Prirodzený logaritmus\">ln</button>\n"
    "<button type=\"button\" data-function=\"log\" data-insert=\"log(\" title=\"Dekadický alebo všeobecný logaritmus\">log</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_FUNCTIONS_3[] =
    "<details class=\"function-group\"><summary>Uhly a goniometria</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"sin\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">sin</button>\n"
    "<button type=\"button\" data-function=\"cos\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">cos</button>\n"
    "<button type=\"button\" data-function=\"tan\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">tan</button>\n"
    "<button type=\"button\" data-function=\"asin\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">asin</button>\n"
    "<button type=\"button\" data-function=\"acos\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">acos</button>\n"
    "<button type=\"button\" data-function=\"atan\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">atan</button>\n"
    "<button type=\"button\" data-function=\"radians\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">radians</button>\n"
    "<button type=\"button\" data-function=\"degrees\" class=\"future\" disabled title=\"Výpočet zatiaľ nie je "
    "implementovaný\">degrees</button>\n"
    "</div></details>\n"
    "<p style=\"color:#adb5c3;font-size:.9rem\">Argumenty oddeľuj ; — napr. pow(2;3). Tmavé tlačidlá ešte "
    "nepočítajú.</p>\n"
    "<a class=\"guide-link\" href=\"/api?lang=sk\">Ako funguje výpočet a API →</a>\n";

static const char NUMFORGE_WEB_PAGE_EN_FUNCTIONS_0[] =
    "<details class=\"function-group\"><summary>Basic</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"abs\" data-insert=\"abs(\" title=\"abs(x)\">abs</button>\n"
    "<button type=\"button\" data-function=\"sign\" data-insert=\"sign(\" title=\"sign(x)\">sign</button>\n"
    "<button type=\"button\" data-function=\"min\" data-insert=\"min(\" title=\"min(a;b;…)\">min</button>\n"
    "<button type=\"button\" data-function=\"max\" data-insert=\"max(\" title=\"max(a;b;…)\">max</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_EN_FUNCTIONS_1[] =
    "<details class=\"function-group\"><summary>Integers</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"gcd\" data-insert=\"gcd(\">gcd</button>\n"
    "<button type=\"button\" data-function=\"lcm\" data-insert=\"lcm(\">lcm</button>\n"
    "<button type=\"button\" data-function=\"mod\" data-insert=\"mod(\">mod</button>\n"
    "<button type=\"button\" data-function=\"factorial\" data-insert=\"factorial(\" "
    "title=\"factorial(n)\">factorial</button>\n"
    "<button type=\"button\" data-function=\"isqrt\" data-insert=\"isqrt(\">isqrt</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_EN_FUNCTIONS_2[] =
    "<details class=\"function-group\"><summary>Powers and logarithms</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"pow\" data-insert=\"pow(\" title=\"pow(x;y)\">pow</button>\n"
    "<button type=\"button\" data-function=\"sqrt\" data-insert=\"sqrt(\">sqrt</button>\n"
    "<button type=\"button\" data-function=\"cbrt\" data-insert=\"cbrt(\">cbrt</button>\n"
    "<button type=\"button\" data-function=\"root\" data-insert=\"root(\">root</button>\n"
    "<button type=\"button\" data-function=\"exp\" data-insert=\"exp(\" title=\"e raised to x\">exp</button>\n"
    "<button type=\"button\" data-function=\"ln\" data-insert=\"ln(\" title=\"Natural logarithm\">ln</button>\n"
    "<button type=\"button\" data-function=\"log\" data-insert=\"log(\" title=\"Common or arbitrary-base logarithm\">log</button>\n"
    "</div></details>\n";

static const char NUMFORGE_WEB_PAGE_EN_FUNCTIONS_3[] =
    "<details class=\"function-group\"><summary>Angles and trigonometry</summary><div class=\"keypad functions\">\n"
    "<button type=\"button\" data-function=\"sin\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">sin</button>\n"
    "<button type=\"button\" data-function=\"cos\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">cos</button>\n"
    "<button type=\"button\" data-function=\"tan\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">tan</button>\n"
    "<button type=\"button\" data-function=\"asin\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">asin</button>\n"
    "<button type=\"button\" data-function=\"acos\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">acos</button>\n"
    "<button type=\"button\" data-function=\"atan\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">atan</button>\n"
    "<button type=\"button\" data-function=\"radians\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">radians</button>\n"
    "<button type=\"button\" data-function=\"degrees\" class=\"future\" disabled title=\"Calculation is not "
    "implemented yet\">degrees</button>\n"
    "</div></details>\n"
    "<p style=\"color:#adb5c3;font-size:.9rem\">Separate arguments with ; — e.g. pow(2;3). Dimmed buttons "
    "are not implemented yet.</p>\n"
    "<a class=\"guide-link\" href=\"/api?lang=en\">How calculation and the API work →</a>\n";

static const char NUMFORGE_FUNCTION_STYLE[] =
    "<style>\n"
    "    .function-group\n"
    "    {\n"
    "        margin-top: 12px;\n"
    "        border: 1px solid #414b5c;\n"
    "        border-radius: 8px;\n"
    "        padding: 12px;\n"
    "    }\n"
    "    .function-group summary\n"
    "    {\n"
    "        cursor: pointer;\n"
    "        font-weight: 600;\n"
    "    }\n"
    "    .keypad.functions\n"
    "    {\n"
    "        grid-template-columns: repeat(auto-fit, minmax(90px, 1fr));\n"
    "    }\n"
    "    .keypad.functions button\n"
    "    {\n"
    "        font-size: .9rem;\n"
    "    }\n"
    "</style>\n";

/*
------------------------------------------------------------------------------------------------------------------------------
    Shared browser logic: input, requests, result expansion, and clipboard.

    Each continuation is sent in order as part of one script. Keep every
    concatenated C string below 4095 UTF-8 bytes when editing page fragments.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char NUMFORGE_WEB_PAGE_SCRIPT_START[] =
    "  <script>\n"
    "    const form = document.querySelector('#calculator');\n"
    "    const expression = document.querySelector('#expression');\n"
    "    const result = document.querySelector('#result');\n"
    "    const expandResult = document.querySelector('#expand-result');\n"
    "    const copyResult = document.querySelector('#copy-result');\n"
    "    const precision = document.querySelector('#precision');\n"
    "    const fullPrecision = document.querySelector('#full-precision');\n"
    "    const english = document.documentElement.lang === 'en';\n"
    "    let generation = 0;\n"
    "    let controller = null;\n"
    "    let copyTimer = null;\n"
    "    let autoTimer = null;\n"
    "    let resultExpanded = false;\n"
    "\n"
    "    function updateResultExpansion()\n"
    "    {\n"
    "        const overflowing = result.scrollHeight > result.clientHeight + 1;\n"
    "        expandResult.style.display = overflowing ? 'inline-block' : 'none';\n"
    "        expandResult.hidden = !overflowing;\n"
    "        if (!overflowing)\n"
    "        {\n"
    "            resultExpanded = false;\n"
    "            result.className = result.className.replace(' expanded', '');\n"
    "        }\n"
    "    }\n"
    "\n"
    "    function toggleResultExpansion()\n"
    "    {\n"
    "        if (expandResult.hidden)\n"
    "        {\n"
    "            return;\n"
    "        }\n"
    "        resultExpanded = !resultExpanded;\n"
    "        result.className =\n"
    "            result.className.replace(' expanded', '') + (resultExpanded ? ' expanded' : '');\n"
    "        expandResult.textContent = resultExpanded ? text.showLess : text.showAll;\n"
    "    }\n"
    "\n"
    "    function invalidate()\n"
    "    {\n"
    "        generation++;\n"
    "        controller?.abort();\n"
    "        clearTimeout(copyTimer);\n"
    "        clearTimeout(autoTimer);\n"
    "        resultExpanded = false;\n"
    "        expandResult.textContent = text.showAll;\n"
    "        result.textContent = '';\n"
    "        result.className = '';\n"
    "        expandResult.hidden = true;\n"
    "        expandResult.style.display = 'none';\n"
    "        copyResult.disabled = true;\n"
    "        copyResult.textContent = text.copy;\n"
    "    }\n"
    "\n"
    "    const text = english ? {\n"
    "        calculating : 'Calculating…',\n"
    "        precision : 'Enter a non-negative whole number of decimal places.',\n"
    "        failure : 'Calculation failed.',\n"
    "        error : 'Error: ',\n"
    "        column : ' at column ',\n"
    "        copy : '⧉ Copy',\n"
    "        copied : '✓ Copied',\n"
    "        showAll : 'Show all',\n"
    "        showLess : 'Show less'\n"
    "    }\n"
    "    : {\n"
    "        calculating : 'Počítam…',\n"
    "        precision : 'Zadaj nezáporný celý počet desatinných miest.',\n"
    "        failure : 'Výpočet zlyhal.',\n"
    "        error : 'Chyba: ',\n"
    "        column : ' v stĺpci ',\n"
    "        copy : '⧉ Kopírovať',\n"
    "        copied : '✓ Skopírované',\n"
    "        showAll : 'Zobraziť všetko',\n"
    "        showLess : 'Zobraziť menej'\n"
    "    };\n"
    "    const slovakStatus = {\n"
    "        'null argument' : 'chýbajúci argument',\n"
    "        'out of memory' : 'nedostatok pamäte',\n"
    "        'invalid argument' : 'neplatný argument',\n"
    "        'invalid token' : 'neplatný token',\n"
    "        'syntax error' : 'syntaktická chyba',\n"
    "        'division by zero' : 'delenie nulou',\n"
    "        'value too large' : 'príliš veľká hodnota',\n"
    "        'scale overflow' : 'pretečenie mierky',\n"
    "        'TLE: time limit exceeded' : 'TLE: prekročený časový limit',\n";

static const char NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_1[] =
    "        'not implemented' : 'funkcia nie je implementovaná',\n"
    "        'wrong number of arguments' : 'nesprávny počet argumentov'\n"
    "    };\n"
    "\n"
    "    function responseError(data)\n"
    "    {\n"
    "        if (!data.status)\n"
    "        {\n"
    "            return data.error || text.failure;\n"
    "        }\n"
    "        const status = english ? data.status : (slovakStatus[data.status] || data.status);\n"
    "        return status + (Number.isInteger(data.column) ? text.column + data.column : '');\n"
    "    }\n"
    "\n"
    "    function scheduleCalculation(delay = 300)\n"
    "    {\n"
    "        invalidate();\n"
    "        if (!expression.value.trim())\n"
    "        {\n"
    "            return;\n"
    "        }\n"
    "        const id = generation;\n"
    "        autoTimer = setTimeout(() => {\n"
    "            if (id === generation)\n"
    "            {\n"
    "                form.requestSubmit();\n"
    "            }\n"
    "        }, delay);\n"
    "    }\n"
    "\n"
    "    expression.addEventListener('input', () => scheduleCalculation());\n"
    "\n"
    "    precision.addEventListener('input', () => scheduleCalculation());\n"
    "\n"
    "    function insertText(text)\n"
    "    {\n"
    "        invalidate();\n"
    "        const start = expression.selectionStart ?? expression.value.length;\n"
    "        const end = expression.selectionEnd ?? start;\n"
    "        expression.setRangeText(text, start, end, 'end');\n"
    "        expression.focus();\n"
    "        scheduleCalculation();\n"
    "    }\n"
    "\n"
    "    function eraseText()\n"
    "    {\n"
    "        invalidate();\n"
    "        const start = expression.selectionStart ?? expression.value.length;\n"
    "        const end = expression.selectionEnd ?? start;\n"
    "        if (start !== end)\n"
    "        {\n"
    "            expression.setRangeText('', start, end, 'end');\n"
    "        }\n"
    "        else if (start > 0)\n"
    "        {\n"
    "            expression.setRangeText('', start - 1, start, 'end');\n"
    "        }\n"
    "        expression.focus();\n"
    "        scheduleCalculation();\n"
    "    }\n"
    "\n"
    "    async function copyText(value)\n"
    "    {\n"
    "        if (navigator.clipboard && window.isSecureContext)\n"
    "        {\n"
    "            await navigator.clipboard.writeText(value);\n"
    "            return;\n"
    "        }\n"
    "        const temporary = document.createElement('textarea');\n"
    "        temporary.value = value;\n"
    "        temporary.style.position = 'fixed';\n"
    "        temporary.style.opacity = '0';\n"
    "        document.body.append(temporary);\n"
    "        temporary.select();\n"
    "        const copied = document.execCommand('copy');\n"
    "        temporary.remove();\n"
    "        if (!copied)\n"
    "        {\n"
    "            throw new Error('copy failed');\n"
    "        }\n"
    "    }\n"
    "\n"
    "    document.querySelectorAll('[data-insert]')\n"
    "        .forEach((button) => button.addEventListener('click', () => insertText(button.dataset.insert)));\n"
    "\n"
    "    document.querySelectorAll('[data-action]')\n"
    "        .forEach((button) => button.addEventListener('click', () => {\n"
    "            if (button.dataset.action === 'clear')\n"
    "            {\n"
    "                invalidate();\n"
    "                expression.value = '';\n"
    "                expression.focus();\n"
    "            }\n"
    "            else if (button.dataset.action === 'backspace')\n"
    "            {\n"
    "                eraseText();\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                form.requestSubmit();\n"
    "            }\n"
    "        }));\n"
    "\n"
    "    copyResult.addEventListener('click', async () => {\n"
    "        if (copyResult.disabled || !result.textContent)\n"
    "        {\n"
    "            return;\n"
    "        }\n"
    "        const id = generation, value = result.textContent;\n"
    "        try\n"
    "        {\n"
    "            await copyText(value);\n"
    "            if (id !== generation)\n"
    "            {\n"
    "                return;\n"
    "            }\n";

static const char NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_2[] =
    "            copyResult.textContent = text.copied;\n"
    "            copyResult.disabled = true;\n"
    "            copyTimer = setTimeout(() => {\n"
    "                if (id === generation)\n"
    "                {\n"
    "                    copyResult.textContent = text.copy;\n"
    "                    copyResult.disabled = !result.textContent;\n"
    "                }\n"
    "            }, 1400);\n"
    "        }\n"
    "        catch (_)\n"
    "        {\n"
    "            if (id === generation)\n"
    "            {\n"
    "                copyResult.textContent = text.copy;\n"
    "            }\n"
    "        }\n"
    "    });\n"
    "\n"
    "    expandResult.addEventListener('click', toggleResultExpansion);\n"
    "\n"
    "    result.addEventListener('click', toggleResultExpansion);\n"
    "\n"
    "    fullPrecision.addEventListener('change', () => {\n"
    "        precision.disabled = fullPrecision.checked;\n"
    "        scheduleCalculation(0);\n"
    "    });\n"
    "\n"
    "    form.addEventListener('submit', async (event) => {\n"
    "        event.preventDefault();\n"
    "        invalidate();\n"
    "        if (!expression.value.trim())\n"
    "        {\n"
    "            return;\n"
    "        }\n"
    "        const id = generation;\n"
    "        controller = new AbortController();\n"
    "        result.className = '';\n"
    "        result.textContent = text.calculating;\n"
    "        copyResult.disabled = true;\n"
    "        copyResult.textContent = text.copy;\n"
    "        try\n"
    "        {\n"
    "            const requestedPrecision = fullPrecision.checked ? 'full' : precision.value;\n"
    "            if (!fullPrecision.checked &&\n"
    "                (!/^[0-9]+$/.test(requestedPrecision) || Number(requestedPrecision) > 10000))\n"
    "            {\n"
    "                throw new Error(english ? 'Precision must be between 0 and 10000.'\n"
    "                                        : 'Presnosť musí byť od 0 do 10000.');\n"
    "            }\n"
    "            if (new TextEncoder().encode(expression.value).length > 4096)\n"
    "            {\n"
    "                throw new Error(english ? 'Expression exceeds 4096 UTF-8 bytes.'\n"
    "                                        : 'Výraz presahuje 4096 UTF-8 bajtov.');\n"
    "            }\n"
    "            const response =\n"
    "                await fetch('/api/evaluate?precision=' + encodeURIComponent(requestedPrecision), {\n"
    "                    method : 'POST',\n"
    "                    headers : {'Content-Type' : 'text/plain; charset=utf-8'},\n"
    "                    body : expression.value,\n"
    "                    signal : controller.signal\n"
    "                });\n"
    "            if (!response.headers.get('content-type')?.includes('application/json'))\n"
    "            {\n"
    "                throw new Error(text.failure);\n"
    "            }\n"
    "            const data = await response.json();\n"
    "            if (id !== generation)\n"
    "            {\n"
    "                return;\n"
    "            }\n"
    "            if (!data || !response.ok || !data.ok)\n"
    "            {\n"
    "                throw new Error(data ? responseError(data) : text.failure);\n"
    "            }\n"
    "            result.textContent = data.result;\n"
    "            copyResult.disabled = false;\n"
    "            updateResultExpansion();\n"
    "        }\n"
    "        catch (error)\n"
    "        {\n"
    "            if (id !== generation || error.name === 'AbortError')\n"
    "            {\n"
    "                return;\n"
    "            }\n"
    "            result.className = 'error';\n"
    "            result.textContent =\n"
    "                text.error + ((error instanceof TypeError || error instanceof SyntaxError)\n"
    "                                  ? text.failure\n"
    "                                  : error.message);\n"
    "            copyResult.disabled = true;\n"
    "            updateResultExpansion();\n"
    "        }\n"
    "    });\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

/*
------------------------------------------------------------------------------------------------------------------------------
    Calculator page assembly. Fragments are sent in this order.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char *const NUMFORGE_WEB_PAGE[] =
{
    NUMFORGE_WEB_PAGE_START,
    NUMFORGE_WEB_PAGE_START_CONT_1,
    NUMFORGE_WEB_PAGE_PRECISION,
    NUMFORGE_WEB_PAGE_RESULT,
    NUMFORGE_WEB_PAGE_KEYPAD,
    NUMFORGE_WEB_PAGE_FUTURE,
    NUMFORGE_FUNCTION_STYLE,
    NUMFORGE_WEB_PAGE_FUNCTIONS_0,
    NUMFORGE_WEB_PAGE_FUNCTIONS_1,
    NUMFORGE_WEB_PAGE_FUNCTIONS_2,
    NUMFORGE_WEB_PAGE_FUNCTIONS_3,
    NUMFORGE_WEB_PAGE_SCRIPT_START,
    NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_1,
    NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_2,
    NULL
};

static const char *const NUMFORGE_WEB_PAGE_EN[] =
{
    NUMFORGE_WEB_PAGE_EN_START,
    NUMFORGE_WEB_PAGE_EN_START_CONT_1,
    NUMFORGE_WEB_PAGE_EN_PRECISION,
    NUMFORGE_WEB_PAGE_EN_RESULT,
    NUMFORGE_WEB_PAGE_EN_KEYPAD,
    NUMFORGE_WEB_PAGE_EN_FUTURE,
    NUMFORGE_FUNCTION_STYLE,
    NUMFORGE_WEB_PAGE_EN_FUNCTIONS_0,
    NUMFORGE_WEB_PAGE_EN_FUNCTIONS_1,
    NUMFORGE_WEB_PAGE_EN_FUNCTIONS_2,
    NUMFORGE_WEB_PAGE_EN_FUNCTIONS_3,
    NUMFORGE_WEB_PAGE_SCRIPT_START,
    NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_1,
    NUMFORGE_WEB_PAGE_SCRIPT_START_CONT_2,
    NULL
};

/*
------------------------------------------------------------------------------------------------------------------------------
    Slovak and English usage/API help fragments.
------------------------------------------------------------------------------------------------------------------------------
*/

static const char NUMFORGE_API_FUNCTIONS_SK[] =
    "<h2>Volania funkcií</h2>\n"
    "<p><code>sqrt(x)</code> alebo <code>√(x)</code> je druhá odmocnina pre x ≥ 0; <code>cbrt(x)</code> "
    "aj pre záporné x. <code>root(x;n)</code> je n-tá odmocnina, celé n od 1 do 10000; záporné x iba pri "
    "nepárnom n. Presné konečné odmocniny zostávajú presné, ostatné používajú max(34, N+4) platných "
    "číslic (plný výpis: 34), potom sa formátujú. Platia časové a pamäťové limity.</p>\n"
    "<p><code>gcd(a;b)</code> a <code>lcm(a;b)</code> vracajú nezáporný najväčší spoločný deliteľ a "
    "najmenší spoločný násobok celých čísel. <code>gcd(0;0)=0</code>; lcm s nulou je 0. "
    "<code>mod(a;b)</code> je celočíselný zvyšok so znamienkom delenca: <code>mod(-7;3)=-1</code>; "
    "deliteľ nesmie byť 0. <code>isqrt(n)</code> je dolná celá odmocnina nezáporného celého čísla: "
    "<code>isqrt(15)=3</code>. Desatinné zápisy celých hodnôt, napr. 4.00, sú povolené.</p>\n"
    "<p>Fungujú aj <code>abs(x)</code> (absolútna hodnota), <code>sign(x)</code> (−1, 0 alebo 1), "
    "<code>min(a;b;…)</code> a <code>max(a;b;…)</code> (najmenej dva argumenty). Porovnávajú vypočítané "
    "hodnoty bez ďalšieho zaokrúhlenia.</p>\n"
    "<p>Názvy používajú iba malé písmená, zátvorky sú povinné a argumenty oddeľuje <code>;</code>. Čiarka "
    "zostáva desatinná: <code>pow(1,5;2)</code> = <code>2.25</code>. Najviac 256 argumentov na volanie.</p>\n"
    "<p>Fungujú <code>pow(x;y)</code> (ako <code>x^y</code>, nezáporný celočíselný exponent) a "
    "<code>factorial(n)</code> (ako <code>n!</code>, celé n od 0 do 10000).</p>\n"
    "<p>Fungujú aj <code>exp(x)</code>, <code>ln(x)</code>, dekadický <code>log(x)</code> a "
    "<code>log(x;b)</code> so základom b. Logaritmovaný výraz musí byť kladný; základ musí byť kladný "
    "a nesmie byť 1.</p>\n"
    "<p>Parser pozná aj nasledujúce volania, no ich výpočet zatiaľ vráti chybu „funkcia nie je "
    "implementovaná“:</p>\n"
    "<p><code>sin(x), cos(x), tan(x), asin(x), acos(x), atan(x), "
    "radians(x), degrees(x)</code></p>\n"
    "<p><code>min</code>/<code>max</code> potrebujú aspoň dva argumenty, <code>atan</code> iba jeden. "
    "Uhly sú v radiánoch. <code>√(x)</code> je alias <code>sqrt(x)</code>.</p>\n"
    "<p><code>exp</code> je celý názov, nie násobenie písmen. Samostatné <code>e</code> ostáva konštanta: "
    "<code>e(2)</code> = <code>e*2</code>, <code>1e3</code> = <code>1*e*3</code>, <code>1E3</code> = "
    "<code>1000</code>. Susedné názvy oddeľ <code>*</code>; <code>ee</code> či <code>esin</code> nie sú "
    "platné názvy.</p>\n";

static const char NUMFORGE_API_FUNCTIONS_EN[] =
    "<h2>Function calls</h2>\n"
    "<p><code>sqrt(x)</code> or <code>√(x)</code> is the square root for x ≥ 0; <code>cbrt(x)</code> also "
    "accepts negative x. <code>root(x;n)</code> takes an integer degree from 1 to 10000; negative x "
    "requires odd n. Exact finite roots remain exact; other roots use max(34, N+4) significant digits "
    "(full output: 34), then output formatting. Time and memory limits still apply.</p>\n"
    "<p><code>gcd(a;b)</code> and <code>lcm(a;b)</code> return the non-negative greatest common divisor "
    "and least common multiple of integers. <code>gcd(0;0)=0</code>; lcm with zero is 0. "
    "<code>mod(a;b)</code> is the integer remainder with the dividend's sign: <code>mod(-7;3)=-1</code>; "
    "a zero divisor is an error. <code>isqrt(n)</code> is the floor square root of a non-negative "
    "integer: <code>isqrt(15)=3</code>. Decimal spellings of whole values, such as 4.00, are accepted.</p>\n"
    "<p>Also available: <code>abs(x)</code> (absolute value), <code>sign(x)</code> (−1, 0 or 1), "
    "<code>min(a;b;…)</code> and <code>max(a;b;…)</code> (at least two arguments). They compare evaluated "
    "values without additional rounding.</p>\n"
    "<p>Names use lowercase letters only, parentheses are mandatory, and <code>;</code> separates "
    "arguments. Comma remains a decimal separator: <code>pow(1,5;2)</code> = <code>2.25</code>. At most "
    "256 arguments per call.</p>\n"
    "<p><code>pow(x;y)</code> works like <code>x^y</code> (non-negative integer exponent); "
    "<code>factorial(n)</code> works like <code>n!</code> (integer n from 0 to 10000).</p>\n"
    "<p>Also available: <code>exp(x)</code>, <code>ln(x)</code>, common <code>log(x)</code>, and "
    "<code>log(x;b)</code> with base b. The logarithm argument must be positive; its base must be "
    "positive and different from 1.</p>\n"
    "<p>The parser also recognizes the following calls, but calculation currently returns “not "
    "implemented”:</p>\n"
    "<p><code>sin(x), cos(x), tan(x), asin(x), acos(x), atan(x), "
    "radians(x), degrees(x)</code></p>\n"
    "<p><code>min</code>/<code>max</code> need at least two arguments; <code>atan</code> only one. "
    "Angles are in radians. <code>√(x)</code> aliases <code>sqrt(x)</code>.</p>\n"
    "<p><code>exp</code> is one name, not a product of letters. Standalone <code>e</code> remains a "
    "constant: <code>e(2)</code> = <code>e*2</code>, <code>1e3</code> = <code>1*e*3</code>, "
    "<code>1E3</code> = <code>1000</code>. Separate adjacent names with <code>*</code>; <code>ee</code> "
    "and <code>esin</code> are not valid names.</p>\n";

static const char NUMFORGE_API_PAGE_START[] =
    "<!doctype html>\n"
    "<html lang=\"sk\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge API</title>\n"
    "  <style>\n"
    "    :root\n"
    "    {\n"
    "        color-scheme: dark;\n"
    "        font-family: system-ui, sans-serif;\n"
    "    }\n"
    "\n"
    "    body\n"
    "    {\n"
    "        max-width: 720px;\n"
    "        margin: 0 auto;\n"
    "        padding: 48px 20px;\n"
    "        background: #111318;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    h1, h2, h3\n"
    "    {\n"
    "        color: #ff9d36;\n"
    "    }\n"
    "\n"
    "    p, li\n"
    "    {\n"
    "        color: #adb5c3;\n"
    "        line-height: 1.55;\n"
    "    }\n"
    "\n"
    "    a\n"
    "    {\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    table\n"
    "    {\n"
    "        width: 100%;\n"
    "        border-collapse: collapse;\n"
    "        margin: 14px 0 24px;\n"
    "    }\n"
    "\n"
    "    th, td\n"
    "    {\n"
    "        padding: 10px;\n"
    "        border-bottom: 1px solid #343b49;\n"
    "        text-align: left;\n"
    "        vertical-align: top;\n"
    "    }\n"
    "\n"
    "    th\n"
    "    {\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    code, pre\n"
    "    {\n"
    "        border-radius: 6px;\n"
    "        background: #1c2028;\n"
    "        font-family: ui-monospace, monospace;\n"
    "    }\n"
    "\n"
    "    code\n"
    "    {\n"
    "        padding: 2px 5px;\n"
    "    }\n"
    "\n"
    "    pre\n"
    "    {\n"
    "        padding: 14px;\n"
    "        overflow-x: auto;\n"
    "    }\n"
    "\n"
    "    .notice\n"
    "    {\n"
    "        padding: 14px;\n"
    "        border-left: 3px solid #ff9d36;\n"
    "        border-radius: 4px;\n"
    "        background: #1c2028;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n";

static const char NUMFORGE_API_PAGE_SK_CONTENT[] =
    "  <header style=\"display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:14px\">\n"
    "    <a href=\"/?lang=sk\">← Späť na kalkulačku</a>\n"
    "    <nav aria-label=\"Výber jazyka\" style=\"display:flex;gap:6px\"><a href=\"/api?lang=sk\" "
    "aria-current=\"true\" title=\"Slovenčina\" style=\"padding:6px 9px;border:1px solid "
    "#ff9d36;border-radius:6px;color:#ffb35e;font-size:.9rem;text-decoration:none\">🇸🇰 SK</a><a "
    "href=\"/api?lang=en\" title=\"English\" style=\"padding:6px 9px;border:1px solid "
    "#3b4352;border-radius:6px;color:#adb5c3;font-size:.9rem;text-decoration:none\">🇬🇧 EN</a></nav>\n"
    "  </header>\n"
    "  <h1>NumForge: použitie a API</h1>\n"
    "  <p>JavaScript iba odošle výraz lokálnemu serveru; samotný výpočet vykoná C aplikácia: tokenizer → "
    "parser → evaluator → BigDecimal → formatter.</p>\n"
    "  <p class=\"notice\">Sčítanie, odčítanie a násobenie sú presné. Nekonečné delenie používa najmenej 34 "
    "významných číslic a half-even; výstup predvolene 10 desatinných miest.</p>\n"
    "  <h2>Čo môžeš zadať do kalkulačky</h2>\n"
    "  <table><tr><th>Prvok</th><th>Príklady</th></tr>\n"
    "  <tr><td>Celé a desatinné čísla</td><td><code>42</code>, <code>-1.5</code>, <code>1,5</code>, "
    "<code>.25</code>, <code>1.</code></td></tr>\n"
    "  <tr><td>Vedecký zápis</td><td><code>1.25E-3</code>, <code>6E4</code>; veľké <code>E</code> je "
    "povinné</td></tr>\n"
    "  <tr><td>Operátory</td><td><code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, "
    "<code>^</code>; mocnina má najvyššiu prioritu medzi binárnymi operátormi, postfixové operácie sa "
    "viažu ešte silnejšie a exponent musí byť nezáporné celé číslo</td></tr>\n"
    "  <tr><td>Zátvorky a znamienka</td><td><code>(2 + 3) * 4</code>, <code>-(2.5E-1) * 8</code></td></tr>\n"
    "  <tr><td>Postfixové operácie</td><td><code>12²</code>, <code>2³</code>, <code>5!</code>; faktoriál "
    "vyžaduje nezáporné celé číslo najviac 10000</td></tr>\n"
    "  <tr><td>Konštanty</td><td><code>π</code>, <code>e</code>, <code>φ</code></td></tr>\n"
    "  <tr><td>Implicitné násobenie</td><td><code>2π</code>, <code>πe</code>, <code>2(3 + "
    "4)</code></td></tr></table>\n"
    "  <p>Operátor <code>%</code> a premenné zatiaľ nie sú podporované.</p>\n"
    "  <p>Konštanty majú uložených 500 desatinných miest. Samostatné malé <code>e</code> znamená Eulerovo "
    "číslo, preto <code>5e</code> znamená <code>5 * e</code> a <code>1e3</code> znamená <code>1 * e * "
    "3</code>. Vedecký zápis vždy používa veľké <code>E</code>: <code>5E-1</code> je <code>0.5</code> a "
    "<code>1E3</code> je <code>1000</code>. Tlačidlá budúcich funkcií sú zámerne neaktívne; názvy sa už "
    "rozpoznávajú, ale výpočet zatiaľ nie je implementovaný.</p>\n"
    "  <h2>Výstupná presnosť</h2>\n"
    "  <p><strong>Desatinné miesta</strong>: 0–10000, predvolene 10; vo vedeckom zápise platia pre "
    "mantisu. Nekonečné delenie používa max(34, N+4) významných číslic. <strong>Plný výstup</strong> "
    "vypne finálne zaokrúhlenie, nie 34-číslicové delenie. <code>1E-40 / 1</code> zostane "
    "<code>1E-40</code>. Medzivýsledky sa môžu zaokrúhliť; vyššia presnosť nepridá číslice ku konštantám.</p>\n";

/*
 * Keep each embedded C string below the ISO C required minimum limit of
 * 4095 characters. GCC diagnoses longer concatenated literals under -Werror.
 */
static const char NUMFORGE_API_PAGE_HTTP[] =
    "  <p>Delenie s konečným desatinným výsledkom je presné v rámci limitov, napríklad <code>7/28 = "
    "0.25</code>. Pracovná presnosť platí pre nekonečné delenia; presnosť zobrazenia zaokrúhli až výstup. "
    "<code>(1E34+1)/1-1E34 = 1</code>.</p>\n"
    "  <p><code>1.2.3</code>, <code>1,2,3</code> a <code>2 3</code> sú chyby, nie násobenie. Platí "
    "<code>(2)3</code>, <code>3!2</code> aj <code>2²3</code>. Násobenie bez znamienka má rovnakú prioritu "
    "ako * a /: <code>6/2(1+2) = 9</code>.</p>\n"
    "  <p>Počet miest nezaručuje presnosť celého výrazu: predvolene <code>(1/3)*3-1 = -1E-34</code>. Pri "
    "odčítaní blízkych zaokrúhlených hodnôt sa presnosť môže stratiť. Plný výstup toto zaokrúhlenie "
    "neodstráni.</p>\n"
    "  <p>Celý výpočet má rozpočet 5 s vrátane parsovania a výstupu; kontroly sú aj v náročných "
    "numerických slučkách. Rušenie je kooperatívne, nie tvrdá real-time záruka. Limity: 64 MiB súčtu "
    "alokácií, 128 KiB jednej alokácie, 65536 bajtov výstupu, hĺbka 256. Prekročenie vráti "
    "<code>TLE</code> alebo <code>value too large</code>. Verejné číselné API tieto aplikačné limity "
    "nemá.</p>\n"
    "  <h2>Lokálne HTTP rozhranie</h2>\n"
    "  <p>Vlastný lokálny klient môže poslať UTF-8 výraz na <code>POST /api/evaluate?precision=10</code>. "
    "Port je 8765 alebo zvolený cez <code>--port</code>. Presnosť je 0–10000 alebo <code>full</code>. "
    "Vstup má limit 4096 bajtov (HTTP 413 pri prekročení); celý musí prísť do 2 s (HTTP 408). Priebežné "
    "posielanie bajtov limit neobnovuje.</p>\n"
    "  <pre>POST /api/evaluate?precision=10 HTTP/1.1\n"
    "Host: 127.0.0.1:8765\n"
    "Content-Type: text/plain; charset=utf-8\n"
    "Content-Length: 6\n"
    "\n"
    "π / 2\n"
    "\n"
    "HTTP/1.1 200 OK\n"
    "{\"ok\":true,\"result\":\"1.5707963268\"}</pre>\n"
    "  <p><code>Content-Length</code> je povinný; bez neho server vráti HTTP 411. Cudzí browser "
    "<code>Origin</code> dostane HTTP 403. Chybný výraz alebo presnosť vráti HTTP 400 JSON s poľami "
    "<code>ok</code>, <code>error</code>, <code>status</code> a od jednotky číslovaným "
    "<code>column</code>. Nedostatok pamäte vráti HTTP 500.</p>\n";

static const char NUMFORGE_API_PAGE_C_LIBRARY[] =
    "  <h2>Verejné C API</h2>\n"
    "  <p>Verejné sú zatiaľ typy <code>BigInt</code> a <code>BigDecimal</code>. Sú opaque: vytvor ich cez "
    "<code>*_create()</code>, uvoľni cez <code>*_destroy()</code>, a reťazce z <code>*_to_string()</code> "
    "uvoľni cez <code>free()</code>.</p>\n"
    "  <h3>BigInt</h3>\n"
    "  <p><code>#include &lt;numforge/bigint.h&gt;</code></p>\n"
    "  <ul><li>Stav: <code>bigint_status_to_string</code></li>\n"
    "  <li>Životný cyklus a text: <code>bigint_create</code>, <code>bigint_destroy</code>, "
    "<code>bigint_copy</code>, <code>bigint_set_string</code>, <code>bigint_to_string</code></li>\n"
    "  <li>Porovnanie: <code>bigint_compare</code>, <code>bigint_is_zero</code>, "
    "<code>bigint_is_one</code>, <code>bigint_is_negative</code>, <code>bigint_is_even</code>, "
    "<code>bigint_is_odd</code></li>\n"
    "  <li>Aritmetika: <code>bigint_abs</code>, <code>bigint_negate</code>, <code>bigint_add</code>, "
    "<code>bigint_sub</code>, <code>bigint_mul</code>, <code>bigint_div</code>, <code>bigint_mod</code>, "
    "<code>bigint_div_mod</code>, <code>bigint_pow</code></li>\n"
    "  <li>Teória čísel: <code>bigint_gcd</code>, <code>bigint_lcm</code>, <code>bigint_factorial</code>, "
    "<code>bigint_is_probable_prime</code>, <code>bigint_is_perfect_square</code></li>\n"
    "  <li>Bity: <code>bigint_and</code>, <code>bigint_or</code>, <code>bigint_xor</code>, "
    "<code>bigint_not</code>, <code>bigint_shift_left</code>, <code>bigint_shift_right</code></li></ul>\n"
    "  <p>Delenie skracuje smerom k nule. <code>bigint_div_mod</code> vyžaduje rozdielne objekty pre "
    "podiel a zvyšok. Bitové AND/OR/XOR prijímajú iba nezáporné hodnoty. Test prvočíselnosti a dokonalej "
    "druhej mocniny vracia status oddelene od výsledku typu <code>bool</code>.</p>\n"
    "  <h3>BigDecimal</h3>\n"
    "  <p><code>#include &lt;numforge/bigdecimal.h&gt;</code></p>\n"
    "  <ul><li>Stav: <code>bigdecimal_status_to_string</code></li>\n"
    "  <li>Životný cyklus a text: <code>bigdecimal_create</code>, <code>bigdecimal_destroy</code>, "
    "<code>bigdecimal_copy</code>, <code>bigdecimal_set_string</code>, <code>bigdecimal_to_string</code></li>\n"
    "  <li>Porovnanie: <code>bigdecimal_compare</code>, <code>bigdecimal_is_zero</code>, "
    "<code>bigdecimal_is_negative</code></li>\n"
    "  <li>Presné operácie: <code>bigdecimal_abs</code>, <code>bigdecimal_negate</code>, "
    "<code>bigdecimal_add</code>, <code>bigdecimal_sub</code>, <code>bigdecimal_mul</code></li>\n"
    "  <li>Ďalšie: konverzie, <code>bigdecimal_pow</code>, <code>bigdecimal_sqrt</code>, "
    "<code>bigdecimal_cbrt</code>, <code>bigdecimal_root</code>, <code>bigdecimal_exp</code>, "
    "<code>bigdecimal_ln</code>, <code>bigdecimal_log10</code>, <code>bigdecimal_log</code>, "
    "významné delenie, konštanty a "
    "formátovanie</li>\n"
    "  <li>Zaokrúhľované operácie: <code>bigdecimal_rescale</code>, <code>bigdecimal_div</code>; režimy "
    "<code>TOWARD_ZERO</code>, <code>AWAY_FROM_ZERO</code>, <code>FLOOR</code>, <code>CEILING</code>, "
    "<code>HALF_UP</code>, <code>HALF_EVEN</code> s prefixom <code>BIGDECIMAL_ROUND_</code></li></ul>\n"
    "  <p>Mutujúce operácie vracajú stavový kód a pri chybe ponechajú cieľovú hodnotu nezmenenú. Úplné "
    "signatúry sú v hlavičkách a podrobnejší prehľad v <code>docs/API.md</code> projekte.</p>\n"
    "</body>\n"
    "</html>\n";

static const char *const NUMFORGE_API_PAGE[] =
{
    NUMFORGE_API_PAGE_START,
    NUMFORGE_API_PAGE_SK_CONTENT,
    NUMFORGE_API_FUNCTIONS_SK,
    NUMFORGE_API_PAGE_HTTP,
    NUMFORGE_API_PAGE_C_LIBRARY,
    NULL
};

static const char NUMFORGE_API_PAGE_EN_START[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge API</title>\n"
    "  <style>\n"
    "    :root\n"
    "    {\n"
    "        color-scheme: dark;\n"
    "        font-family: system-ui, sans-serif;\n"
    "    }\n"
    "\n"
    "    body\n"
    "    {\n"
    "        max-width: 720px;\n"
    "        margin: 0 auto;\n"
    "        padding: 48px 20px;\n"
    "        background: #111318;\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    .page-header\n"
    "    {\n"
    "        display: flex;\n"
    "        flex-wrap: wrap;\n"
    "        align-items: center;\n"
    "        justify-content: space-between;\n"
    "        gap: 14px;\n"
    "    }\n"
    "\n"
    "    h1, h2, h3\n"
    "    {\n"
    "        color: #ff9d36;\n"
    "    }\n"
    "\n"
    "    h1\n"
    "    {\n"
    "        margin: 0;\n"
    "    }\n"
    "\n"
    "    p, li\n"
    "    {\n"
    "        color: #adb5c3;\n"
    "        line-height: 1.55;\n"
    "    }\n"
    "\n"
    "    a\n"
    "    {\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    .language-switch\n"
    "    {\n"
    "        display: flex;\n"
    "        gap: 6px;\n"
    "    }\n"
    "\n"
    "    .language-switch a\n"
    "    {\n"
    "        padding: 6px 9px;\n"
    "        border: 1px solid #3b4352;\n"
    "        border-radius: 6px;\n"
    "        color: #adb5c3;\n"
    "        font-size: .9rem;\n"
    "        text-decoration: none;\n"
    "    }\n"
    "\n"
    "    .language-switch a[aria-current=\"true\"]\n"
    "    {\n"
    "        border-color: #ff9d36;\n"
    "        color: #ffb35e;\n"
    "    }\n"
    "\n"
    "    table\n"
    "    {\n"
    "        width: 100%;\n"
    "        border-collapse: collapse;\n"
    "        margin: 14px 0 24px;\n"
    "    }\n"
    "\n"
    "    th, td\n"
    "    {\n"
    "        padding: 10px;\n"
    "        border-bottom: 1px solid #343b49;\n"
    "        text-align: left;\n"
    "        vertical-align: top;\n"
    "    }\n"
    "\n"
    "    th\n"
    "    {\n"
    "        color: #edf0f5;\n"
    "    }\n"
    "\n"
    "    code, pre\n"
    "    {\n"
    "        border-radius: 6px;\n"
    "        background: #1c2028;\n"
    "        font-family: ui-monospace, monospace;\n"
    "    }\n"
    "\n"
    "    code\n"
    "    {\n"
    "        padding: 2px 5px;\n"
    "    }\n"
    "\n"
    "    pre\n"
    "    {\n"
    "        padding: 14px;\n"
    "        overflow-x: auto;\n"
    "    }\n"
    "\n"
    "    .notice\n"
    "    {\n"
    "        padding: 14px;\n"
    "        border-left: 3px solid #ff9d36;\n"
    "        border-radius: 4px;\n"
    "        background: #1c2028;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <header class=\"page-header\">\n"
    "    <a href=\"/?lang=en\">← Back to calculator</a>\n"
    "    <nav class=\"language-switch\" aria-label=\"Language selection\"><a href=\"/api?lang=sk\" lang=\"sk\" "
    "title=\"Slovenčina\">🇸🇰 SK</a><a href=\"/api?lang=en\" lang=\"en\" aria-current=\"true\" "
    "title=\"English\">🇬🇧 EN</a></nav>\n"
    "  </header>\n"
    "  <h1>NumForge: usage and API</h1>\n"
    "  <p>JavaScript only sends the expression to the local server; the C application performs the "
    "calculation: tokenizer → parser → evaluator → BigDecimal → formatter.</p>\n"
    "  <p class=\"notice\">Addition, subtraction, and multiplication are exact. Non-terminating division "
    "uses at least 34 significant digits with half-even rounding; output defaults to 10 decimal places.</p>\n"
    "  <h2>What you can enter</h2>\n"
    "  <table><tr><th>Element</th><th>Examples</th></tr>\n"
    "  <tr><td>Integers and decimals</td><td><code>42</code>, <code>-1.5</code>, <code>1,5</code>, "
    "<code>.25</code>, <code>1.</code></td></tr>\n"
    "  <tr><td>Scientific notation</td><td><code>1.25E-3</code>, <code>6E4</code>; uppercase "
    "<code>E</code> is required</td></tr>\n"
    "  <tr><td>Operators</td><td><code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, "
    "<code>^</code>; power has the highest binary-operator precedence, postfix operations bind more "
    "tightly, and the exponent must be a non-negative integer</td></tr>\n"
    "  <tr><td>Parentheses and signs</td><td><code>(2 + 3) * 4</code>, <code>-(2.5E-1) * 8</code></td></tr>\n";

static const char NUMFORGE_API_PAGE_EN_START_CONT_1[] =
    "  <tr><td>Postfix operations</td><td><code>12²</code>, <code>2³</code>, <code>5!</code>; factorial "
    "requires a non-negative integer no greater than 10000</td></tr>\n"
    "  <tr><td>Constants</td><td><code>π</code>, <code>e</code>, <code>φ</code></td></tr>\n"
    "  <tr><td>Implicit multiplication</td><td><code>2π</code>, <code>πe</code>, <code>2(3 + "
    "4)</code></td></tr></table>\n"
    "  <p><code>%</code> and variables are not supported yet.</p>\n"
    "  <p>Constants store 500 decimal places. Standalone lowercase <code>e</code> means Euler's number: "
    "<code>5e</code> means <code>5 * e</code> and <code>1e3</code> means <code>1 * e * 3</code>. "
    "Scientific notation always uses uppercase <code>E</code>: <code>5E-1</code> is <code>0.5</code> and "
    "<code>1E3</code> is <code>1000</code>. Dimmed buttons represent recognized calls whose calculations "
    "are not implemented yet; root, exponential and logarithmic controls are active.</p>\n";

static const char NUMFORGE_API_PAGE_EN_DETAILS[] =
    "  <p>Terminating decimal division is exact within resource limits, e.g. <code>7/28 = 0.25</code>. "
    "Working precision applies to recurring quotients; display precision rounds the final output. "
    "<code>(1E34+1)/1-1E34 = 1</code>.</p>\n"
    "  <p><code>1.2.3</code>, <code>1,2,3</code> and <code>2 3</code> are errors, not products. "
    "<code>(2)3</code>, <code>3!2</code> and <code>2²3</code> remain valid. Implicit multiplication has "
    "the same precedence as * and /: <code>6/2(1+2) = 9</code>.</p>\n"
    "  <p>Output places do not guarantee whole-expression accuracy: by default <code>(1/3)*3-1 = "
    "-1E-34</code>. Subtracting nearby rounded values can lose accuracy. Full output does not undo this "
    "rounding.</p>\n"
    "  <h2>Output precision</h2>\n"
    "  <p><strong>Decimal places</strong>: 0–10000, default 10; applies to the mantissa in scientific "
    "notation. Non-terminating division uses max(34, N+4) significant digits. <strong>Full "
    "output</strong> skips final rounding, not 34-digit division. <code>1E-40 / 1</code> stays "
    "<code>1E-40</code>. Intermediate results can be rounded; higher precision does not add digits to "
    "constants.</p>\n"
    "  <p>The whole calculation has a 5 s budget, including parsing and output, checked inside expensive "
    "numeric loops. Cancellation is cooperative, not a hard real-time guarantee. Limits: 64 MiB "
    "cumulative allocations, 128 KiB per allocation, 65536 output bytes, depth 256. Exceeding them "
    "returns <code>TLE</code> or <code>value too large</code>. Public numeric APIs do not have these "
    "application limits.</p>\n"
    "  <h2>Local HTTP interface</h2>\n"
    "  <p>A local client sends UTF-8 expressions to <code>POST /api/evaluate?precision=10</code>. Port is "
    "8765 or selected with <code>--port</code>. Precision is 0–10000 or <code>full</code>. Input is "
    "limited to 4096 bytes (HTTP 413 if exceeded) and must arrive completely within 2 s (HTTP 408). "
    "Individual bytes do not restart the deadline.</p>\n"
    "  <pre>POST /api/evaluate?precision=10 HTTP/1.1\n"
    "Host: 127.0.0.1:8765\n"
    "Content-Type: text/plain; charset=utf-8\n"
    "Content-Length: 6\n"
    "\n"
    "π / 2\n"
    "\n"
    "HTTP/1.1 200 OK\n"
    "{\"ok\":true,\"result\":\"1.5707963268\"}</pre>\n"
    "  <p><code>Content-Length</code> is required; without it the server returns HTTP 411. A foreign "
    "browser <code>Origin</code> gets HTTP 403. Invalid expressions or precision return HTTP 400 JSON "
    "with <code>ok</code>, <code>error</code>, <code>status</code>, and a one-based <code>column</code>. "
    "Out-of-memory calculation failures return HTTP 500.</p>\n";

static const char NUMFORGE_API_PAGE_EN_C_LIBRARY[] =
    "  <h2>Public C API</h2>\n"
    "  <p>The public types are currently <code>BigInt</code> and <code>BigDecimal</code>. They are "
    "opaque: create them with <code>*_create()</code>, release them with <code>*_destroy()</code>, and "
    "release strings from <code>*_to_string()</code> with <code>free()</code>.</p>\n"
    "  <h3>BigInt</h3>\n"
    "  <p><code>#include &lt;numforge/bigint.h&gt;</code></p>\n"
    "  <ul><li>Status: <code>bigint_status_to_string</code></li>\n"
    "  <li>Lifecycle and text: <code>bigint_create</code>, <code>bigint_destroy</code>, "
    "<code>bigint_copy</code>, <code>bigint_set_string</code>, <code>bigint_to_string</code></li>\n"
    "  <li>Comparison: <code>bigint_compare</code>, <code>bigint_is_zero</code>, "
    "<code>bigint_is_one</code>, <code>bigint_is_negative</code>, <code>bigint_is_even</code>, "
    "<code>bigint_is_odd</code></li>\n"
    "  <li>Arithmetic: <code>bigint_abs</code>, <code>bigint_negate</code>, <code>bigint_add</code>, "
    "<code>bigint_sub</code>, <code>bigint_mul</code>, <code>bigint_div</code>, <code>bigint_mod</code>, "
    "<code>bigint_div_mod</code>, <code>bigint_pow</code></li>\n"
    "  <li>Number theory: <code>bigint_gcd</code>, <code>bigint_lcm</code>, "
    "<code>bigint_factorial</code>, <code>bigint_is_probable_prime</code>, "
    "<code>bigint_is_perfect_square</code></li>\n"
    "  <li>Bits: <code>bigint_and</code>, <code>bigint_or</code>, <code>bigint_xor</code>, "
    "<code>bigint_not</code>, <code>bigint_shift_left</code>, <code>bigint_shift_right</code></li></ul>\n"
    "  <p>Division truncates toward zero. <code>bigint_div_mod</code> requires distinct objects for "
    "quotient and remainder. Bitwise AND/OR/XOR accept non-negative values only. Probable-prime and "
    "perfect-square checks return status separately from their <code>bool</code> result.</p>\n"
    "  <h3>BigDecimal</h3>\n"
    "  <p><code>#include &lt;numforge/bigdecimal.h&gt;</code></p>\n"
    "  <ul><li>Status: <code>bigdecimal_status_to_string</code></li>\n"
    "  <li>Lifecycle and text: <code>bigdecimal_create</code>, <code>bigdecimal_destroy</code>, "
    "<code>bigdecimal_copy</code>, <code>bigdecimal_set_string</code>, <code>bigdecimal_to_string</code></li>\n"
    "  <li>Comparison: <code>bigdecimal_compare</code>, <code>bigdecimal_is_zero</code>, "
    "<code>bigdecimal_is_negative</code></li>\n"
    "  <li>Exact operations: <code>bigdecimal_abs</code>, <code>bigdecimal_negate</code>, "
    "<code>bigdecimal_add</code>, <code>bigdecimal_sub</code>, <code>bigdecimal_mul</code></li>\n"
    "  <li>Further operations: powers, roots, <code>bigdecimal_exp</code>, <code>bigdecimal_ln</code>, "
    "<code>bigdecimal_log10</code>, <code>bigdecimal_log</code>, significant division, constants and "
    "formatting</li>\n"
    "  <li>Rounded operations: <code>bigdecimal_rescale</code>, <code>bigdecimal_div</code>; modes "
    "<code>TOWARD_ZERO</code>, <code>AWAY_FROM_ZERO</code>, <code>FLOOR</code>, <code>CEILING</code>, "
    "<code>HALF_UP</code>, <code>HALF_EVEN</code> with the <code>BIGDECIMAL_ROUND_</code> prefix</li></ul>\n"
    "  <p>Mutating operations return a status code and leave the destination value unchanged on failure. "
    "Full signatures are in the headers and a more detailed overview is in <code>docs/API.md</code>.</p>\n"
    "</body>\n"
    "</html>\n";

static const char *const NUMFORGE_API_PAGE_EN[] =
{
    NUMFORGE_API_PAGE_EN_START,
    NUMFORGE_API_PAGE_EN_START_CONT_1,
    NUMFORGE_API_FUNCTIONS_EN,
    NUMFORGE_API_PAGE_EN_DETAILS,
    NUMFORGE_API_PAGE_EN_C_LIBRARY,
    NULL
};

#endif
