#ifndef NUMFORGE_WEB_PAGE_H
#define NUMFORGE_WEB_PAGE_H

/*
------------------------------------------------------------------------------------------------------------------------------
    Small calculator and API-guide pages embedded in the server executable.
    Keeping them here makes numforge_web self-contained: no Node.js, assets,
    or working-directory setup is required to use the local calculator.
------------------------------------------------------------------------------------------------------------------------------
*/
static const char NUMFORGE_WEB_PAGE[] =
    "<!doctype html>\n"
    "<html lang=\"sk\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge</title>\n"
    "  <style>\n"
    "    :root { color-scheme: dark; font-family: system-ui, sans-serif; }\n"
    "    body { max-width: 720px; margin: 0 auto; padding: 48px 20px; background: #111318; color: #edf0f5; }\n"
    "    h1 { margin: 0; color: #ff9d36; }\n"
    "    p { color: #adb5c3; line-height: 1.55; }\n"
    "    a { color: #ffb35e; }\n"
    "    form { display: flex; gap: 10px; margin-top: 28px; }\n"
    "    input { min-width: 0; flex: 1; padding: 13px; border: 1px solid #3b4352; border-radius: 8px; background: #1c2028; color: inherit; font: 1rem ui-monospace, monospace; }\n"
    "    button { padding: 12px 18px; border: 0; border-radius: 8px; background: #ff9d36; color: #17110a; font-weight: 700; cursor: pointer; }\n"
    "    .result-panel { margin-top: 22px; padding: 16px; border-radius: 8px; background: #1c2028; }\n"
    "    .result-label { display: block; margin-bottom: 7px; color: #adb5c3; font-size: .84rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; }\n"
    "    #result { display: block; min-height: 1.5em; font: 1.2rem ui-monospace, monospace; overflow-wrap: anywhere; }\n"
    "    #result.error { color: #ff8888; }\n"
    "    .guide-link { display: inline-block; margin-top: 22px; }\n"
    "    code, pre { border-radius: 6px; background: #1c2028; font-family: ui-monospace, monospace; }\n"
    "    code { padding: 2px 5px; }\n"
    "    pre { padding: 14px; overflow-x: auto; }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <h1>NumForge</h1>\n"
    "  <p>Zapíš výraz a NumForge ho vyhodnotí priamo cez C parser a presný BigDecimal.</p>\n"
    "  <form id=\"calculator\">\n"
    "    <input id=\"expression\" aria-label=\"Matematický výraz\" value=\"0.1 + 0.2\" autocomplete=\"off\" autofocus>\n"
    "    <button type=\"submit\">Vypočítať</button>\n"
    "  </form>\n"
    "  <section class=\"result-panel\" aria-live=\"polite\">\n"
    "    <span class=\"result-label\">Výsledok</span>\n"
    "    <output id=\"result\">Pripravené</output>\n"
    "  </section>\n"
    "  <a class=\"guide-link\" href=\"/api\">Ako funguje výpočet a API →</a>\n"
    "  <script>\n"
    "    const form = document.querySelector('#calculator');\n"
    "    const expression = document.querySelector('#expression');\n"
    "    const result = document.querySelector('#result');\n"
    "    form.addEventListener('submit', async (event) => {\n"
    "      event.preventDefault();\n"
    "      result.className = ''; result.textContent = 'Počítam…';\n"
    "      try {\n"
    "        const response = await fetch('/api/evaluate', { method: 'POST', headers: { 'Content-Type': 'text/plain; charset=utf-8' }, body: expression.value });\n"
    "        const data = await response.json();\n"
    "        if (!response.ok || !data.ok) throw new Error(data.error || 'Výpočet zlyhal.');\n"
    "        result.textContent = data.result;\n"
    "      } catch (error) {\n"
    "        result.className = 'error'; result.textContent = 'Chyba: ' + error.message;\n"
    "      }\n"
    "    });\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

static const char NUMFORGE_API_PAGE[] =
    "<!doctype html>\n"
    "<html lang=\"sk\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>NumForge API</title>\n"
    "  <style>\n"
    "    :root { color-scheme: dark; font-family: system-ui, sans-serif; }\n"
    "    body { max-width: 720px; margin: 0 auto; padding: 48px 20px; background: #111318; color: #edf0f5; }\n"
    "    h1, h2 { color: #ff9d36; }\n"
    "    p, li { color: #adb5c3; line-height: 1.55; }\n"
    "    a { color: #ffb35e; }\n"
    "    code, pre { border-radius: 6px; background: #1c2028; font-family: ui-monospace, monospace; }\n"
    "    code { padding: 2px 5px; }\n"
    "    pre { padding: 14px; overflow-x: auto; }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <a href=\"/\">← Späť na kalkulačku</a>\n"
    "  <h1>NumForge API</h1>\n"
    "  <p>Stránka kalkulačky posiela výraz do C aplikácie. Tá ho tokenizuje, spracuje parserom a vyhodnotí cez BigDecimal, takže napríklad <code>0.1 + 0.2</code> vráti presne <code>0.3</code>.</p>\n"
    "  <h2>Použitie v kalkulačke</h2>\n"
    "  <p>Zadaj desatinné čísla, <code>+</code>, <code>-</code>, <code>*</code>, <code>/</code> a zátvorky. Napríklad <code>(12.5 - 2.5) / 4</code>.</p>\n"
    "  <h2>HTTP rozhranie</h2>\n"
    "  <p>Pre vlastného lokálneho klienta pošli výraz ako obyčajný text do <code>POST /api/evaluate</code>. Odpoveď je JSON.</p>\n"
    "  <pre>POST /api/evaluate\nContent-Type: text/plain\n\n0.1 + 0.2\n\n{\"ok\":true,\"result\":\"0.3\"}</pre>\n"
    "  <p>Pri chybe odpoveď obsahuje <code>ok: false</code>, opis chyby a príslušný HTTP status 400.</p>\n"
    "</body>\n"
    "</html>\n";

#endif
