# Run after CTest in a fresh GCC coverage build. No percentage gate.
if(NOT DEFINED BUILD_DIR OR NOT DEFINED GCOV)
    message(FATAL_ERROR "BUILD_DIR and GCOV are required")
endif()
file(GLOB_RECURSE notes "${BUILD_DIR}/CMakeFiles/*.gcno")
if(NOT notes)
    message(FATAL_ERROR "No instrumented objects found; configure with NUMFORGE_ENABLE_COVERAGE=ON")
endif()
set(report "${BUILD_DIR}/coverage")
file(MAKE_DIRECTORY "${report}")
file(WRITE "${report}/summary.txt" "NumForge gcov line and branch coverage (src only)\n")
foreach(note IN LISTS notes)
    if(NOT note MATCHES "/src/.*\\.gcno$")
        continue()
    endif()
    execute_process(COMMAND "${GCOV}" -b -c -p "${note}"
        WORKING_DIRECTORY "${report}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    file(APPEND "${report}/summary.txt" "\n${output}${errors}")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "gcov failed for ${note}: ${errors}")
    endif()
endforeach()
message(STATUS "Coverage report: ${report}/summary.txt")
